<a href="https://colab.research.google.com/github/yaswanthdongara/python_practice/blob/main/Sep_23.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr = np.array([-3.14,3.121,12.99,25.2512])

In [10]:
#around
a = np.around(arr)
for ele in a:
  print(ele,end=' ')
print()
b = np.around(arr,2)
print(b)

-3.0 3.0 13.0 25.0 
[-3.14  3.12 12.99 25.25]


In [14]:
#floor
#arr = [-3.14,3.121,12.99,25.2512]
a = np.floor(arr)
for ele in a:
  print(ele,end=' ')
print()
#ceil
a = np.ceil(arr)
for ele in a:
  print(ele,end=' ')
print()

-4.0 3.0 12.0 25.0 
-3.0 4.0 13.0 26.0 


In [19]:
#gcd
n1 = 12
n2 = 22
gcd = np.gcd(n1,n2)
print(gcd)
#gcd of nd array object
arr = np.array([12,8,14,22])
gcd = np.gcd.reduce(arr)
print(gcd)

2
2


In [20]:
#lcm
n1 = 12
n2 = 25
lcm = np.lcm(n1,n2)
print(lcm)
#lcm of nd array object
arr = np.array([12,8,14,22])
lcm = np.lcm.reduce(arr)
print(lcm)

300
1848


In [35]:
#descrete differences
arr = np.array([10,20,30,40,50])
dd = np.diff(arr)
print(dd)
#finding descrete difference n times
arr = np.array([10,100,1000,10000,100000,1000000])
dd = np.diff(arr,4)
print(dd)
#decrete differences on 2d array
arr = np.array([12,25,8,11,18,17,21,22,7]).reshape(3,3)
dd = np.diff(arr,axis=0,n=2)
print(dd)

[10 10 10 10]
[ 65610 656100]
[[ 11  11 -19]]
